(define (make-account balance password)
    (let ((incorrect-consecutive-passwords 0))
        (define (withdraw amount)
            (if (>= balance amount)
                (begin
                    (set! balance (- balance amount))
                    balance)
                "Not enough balance"
            )
        )

        (define (deposit amount)
            (set! balance (+ balance amount))
            balance
        )

        (define (password-valid? given-password)
            (and (symbol? password) (eq? password given-password))
        )

        (define (check-incorrect-consecutive-passwords-count)
            (if (> incorrect-consecutive-passwords 7)
                (call-the-cops)
            )
        )

        (define (call-the-cops)
            (display "*********************")
            (newline)
            (display "CALLING THE COPS!") 
            (newline)
            (display "*********************")
            (newline)
        )

        (lambda (message given-password)
            (if (password-valid? given-password)
                (begin
                    (set! incorrect-consecutive-passwords 0)
                    (cond ((eq? message 'withdraw) withdraw)
                        ((eq? message 'deposit) deposit)
                        (else (error "Invalid message passed -- MAKE-ACCOUNT" message))
                    ))
                (begin
                    (set! incorrect-consecutive-passwords (+ incorrect-consecutive-passwords 1))
                    (check-incorrect-consecutive-passwords-count)
                    (lambda (a) "Invalid password")
                )
            )
        )
    )
)

(define account (make-account 100 'some-password))
(display ((account 'withdraw 'some-wrong-password) 15)) (newline)
(display ((account 'withdraw 'some-wrong-password) 15)) (newline)
(display ((account 'withdraw 'some-wrong-password) 15)) (newline)
(display ((account 'withdraw 'some-wrong-password) 15)) (newline)
(display ((account 'withdraw 'some-wrong-password) 15)) (newline)
(display ((account 'withdraw 'some-wrong-password) 15)) (newline)
(display ((account 'withdraw 'some-wrong-password) 15)) (newline)
(display ((account 'withdraw 'some-wrong-password) 15)) (newline)
(display ((account 'withdraw 'some-wrong-password) 15)) (newline)
(display ((account 'withdraw 'some-wrong-password) 15)) (newline)
(display ((account 'withdraw 'some-wrong-password) 15)) (newline)
(display ((account 'withdraw 'some-wrong-password) 15)) (newline)