; Regular scheme program to solve the multiple dwelling puzzle
(define (try-all options f)
    (if (not (null? options))
        (begin 
            (f (car options))
            (try-all (cdr options) f)
        )
    )
)

(define (distinct? l)
    (cond ((null? l) true)
        ((null? (cdr l)) true)
        ((member (car l) (cdr l)) false)
        (else (distinct? (cdr l)))
    )
)

(define (multiple-dwelling)
    (define options (list 1 2 3 4 5))
    (try-all options (lambda (baker)
        (if (not (= baker 5))
            (try-all options (lambda (cooper)
                (if (not (= cooper 1))
                    (try-all options (lambda (fletcher)
                        (if (and 
                                (and (not (= fletcher 1)) (not (= fletcher 5)))
                                (> (abs (- fletcher cooper)) 1)
                        )
                            (try-all options (lambda (miller)
                                (if (> miller cooper) 
                                    (try-all options (lambda (smith)
                                        (if (and 
                                                (> (abs (- smith fletcher)) 1)
                                                (distinct? (list baker cooper fletcher miller smith))
                                        )
                                            (display 
                                                (list 
                                                    (list 'baker baker)
                                                    (list 'cooper cooper)
                                                    (list 'fletcher fletcher)
                                                    (list 'miller miller)
                                                    (list 'smith smith)
                                                )
                                            )
                                        )
                                    ))
                                )
                            ))
                        )
                    ))
                )
            ))
        )
    ))
)
(multiple-dwelling)